from __future__ import annotations

import os
import shlex
import shutil
from pathlib import Path
from typing import Any

YAML_TEMPLATE = """# DecisionDrift configuration
# Generated by `decisiondrift init`

llm:
  api_key: null  # Set DECISIONDRIFT_LLM_API_KEY or configure here
  model: gpt-4o
  base_url: null  # Use for Ollama, Groq, etc.

adr_dir: docs/adr

# Custom rule packs — additional rules beyond those generated from ADRs.
# Rules are combined with ADR-derived rules during enforcement.
# Supported types: dependency, import, path, api, config
# Supported actions: block, require_approval, warn, info
# rules:
#   - match: deprecated-library
#     type: dependency
#     action: block
#     description: "Block usage of deprecated library"
#   - match: old_module
#     type: import
#     action: warn
#     description: "Warn on imports from old_module"
"""

CI_GITHUB_TEMPLATE = """name: DecisionDrift Governance
on: [pull_request]

jobs:
  governance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: madhan-karthikeyan/DecisionDrift@v1
        with:
          github-token: ${{{{ secrets.GITHUB_TOKEN }}}}
          fail-on-violation: true
"""


def init_project(
    repo_path: Path,
    non_interactive: bool = False,
    template: str | None = None,
    adr_dir: str = "docs/adr",
    generate_ci: bool = False,
) -> dict[str, Any]:
    result: dict[str, Any] = {
        "repo_path": str(repo_path),
        "steps_taken": [],
        "adrs_approved": 0,
        "hook_installed": False,
        "config_written": False,
        "ci_written": False,
    }

    resolved_adr = repo_path / adr_dir

    # Step 1: Bootstrap ADRs
    suggestions = _run_bootstrap(repo_path, resolved_adr)
    if suggestions:
        approved_ids = _handle_adr_approval(suggestions, resolved_adr, non_interactive)
        result["adrs_approved"] = len(approved_ids)
        result["steps_taken"].append(f"Generated {len(suggestions)} ADR(s), approved {len(approved_ids)}")
    else:
        result["steps_taken"].append("No candidate ADRs generated")

    # Step 2: Install pre-commit hook
    hook_installed = _install_hook(repo_path, resolved_adr, non_interactive)
    result["hook_installed"] = hook_installed
    if hook_installed:
        result["steps_taken"].append("Pre-commit hook installed")

    # Step 3: Generate decisiondrift.yml
    config_path = repo_path / "decisiondrift.yml"
    if not config_path.exists():
        _write_config(config_path, adr_dir)
        result["config_written"] = True
        result["steps_taken"].append("Generated decisiondrift.yml")
    else:
        result["steps_taken"].append("decisiondrift.yml already exists (skipped)")

    # Step 4: Optionally generate CI config
    if generate_ci:
        ci_path = repo_path / ".github" / "workflows" / "decisiondrift.yml"
        if not ci_path.exists():
            _write_ci(ci_path)
            result["ci_written"] = True
            result["steps_taken"].append("Generated .github/workflows/decisiondrift.yml")
        else:
            result["steps_taken"].append("CI workflow already exists (skipped)")

    return result


def _run_bootstrap(repo_path: Path, adr_dir: Path) -> list[Any]:
    from decisiondrift.bootstrap.bootstrapper import bootstrap

    suggestions = bootstrap(
        repo_path=str(repo_path),
        adr_dir=str(adr_dir),
        dry_run=False,
        min_confidence="low",
    )
    return suggestions


def _handle_adr_approval(suggestions: list[Any], adr_dir: Path, non_interactive: bool) -> list[str]:
    from decisiondrift.adr_manager.commands import approve_adr

    approved: list[str] = []
    for suggestion in suggestions:
        adr = suggestion.adr
        adr_id = adr.id

        if non_interactive:
            approve_adr(str(adr_dir), adr_id)
            approved.append(adr_id)
            print(f"  ✓ {adr_id}: {adr.title} (auto-approved)")
        else:
            print(f"\n  Candidate: {adr_id}: {adr.title}")
            print(f"    Type: {adr.type or 'N/A'}")
            if adr.prohibitions:
                print(f"    Prohibitions: {', '.join(adr.prohibitions)}")
            if adr.rationale:
                short = adr.rationale[:200].replace("\n", " ")
                print(f"    Rationale: {short}...")
            resp = input("    Approve this ADR? [Y/n] ").strip().lower()
            if resp in ("", "y", "yes"):
                approve_adr(str(adr_dir), adr_id)
                approved.append(adr_id)
                print(f"    → Approved")
            else:
                print(f"    → Skipped")
    return approved


def _install_hook(repo_path: Path, adr_dir: Path, non_interactive: bool) -> bool:
    hook_path = repo_path / ".git" / "hooks" / "pre-commit"
    if hook_path.exists():
        if non_interactive:
            return False
        resp = input("  Pre-commit hook already exists. Overwrite? [y/N] ").strip().lower()
        if resp not in ("y", "yes"):
            print("  → Hook installation skipped")
            return False

    if non_interactive:
        print("  Installing pre-commit hook...")
    else:
        resp = input("  Install pre-commit hook? [Y/n] ").strip().lower()
        if resp not in ("", "y", "yes"):
            print("  → Hook installation skipped")
            return False

    hook_path.parent.mkdir(parents=True, exist_ok=True)
    hook_content = "#!/bin/sh\nexec decisiondrift enforce --staged --repo " + shlex.quote(str(repo_path))
    hook_content += " --adr-dir " + shlex.quote(str(adr_dir))
    hook_path.write_text(hook_content.strip() + "\n")
    hook_path.chmod(0o755)
    print("  → Pre-commit hook installed")
    return True


def _write_config(config_path: Path, adr_dir: str) -> None:
    config_path.parent.mkdir(parents=True, exist_ok=True)
    content = YAML_TEMPLATE.replace("docs/adr", adr_dir)
    config_path.write_text(content)


def _write_ci(ci_path: Path) -> None:
    ci_path.parent.mkdir(parents=True, exist_ok=True)
    ci_path.write_text(CI_GITHUB_TEMPLATE)
