from backend.extensions import db
from .user import User
from .patient import Patient
from .doctor import Doctor
from .admin import Admin
from .appointment import Appointment
from .treatment import Treatment
from .department import Department
from .doctoravailability import DoctorAvailability
from .medication import Medication
from .payment import PaymentIntent